# Generated by Django 5.0 on 2024-02-09 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2',
        ),
        migrations.AddField(
            model_name='team',
            name='leader_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leader_email', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='member1_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member1_email', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='member2_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member2_email', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
