# Generated by Django 5.0 on 2024-02-09 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam', '0002_remove_team_leader_remove_team_member1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member1_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2_email',
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leading_teams', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='member1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_members1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='member2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_members2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
