# Generated by Django 5.0 on 2024-02-10 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam', '0003_remove_team_leader_email_remove_team_member1_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='udyam.event'),
        ),
    ]
