# Generated by Django 5.0 on 2024-01-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
