# Generated by Django 5.0 on 2024-01-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_user_otp_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
