# Generated by Django 5.0 on 2024-01-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_user_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
