# Generated by Django 5.0 on 2024-01-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(choices=[('FIRST', '1st year'), ('SECOND', '2nd year'), ('THIRD', '3rd year'), ('FORTH', '4th year'), ('FIFTH', '5th year')], default=1),
            preserve_default=False,
        ),
    ]
