# Generated by Django 5.0 on 2024-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_user_college_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
