# Generated by Django 5.0 on 2024-01-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
