# Generated by Django 5.0 on 2024-01-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_user_college_user_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
