# Generated by Django 5.0 on 2024-01-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_remove_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name',
        ),
    ]
