# Generated by Django 5.0 on 2024-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_rename_username_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('AskedWhen', models.DateTimeField()),
                ('question', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(),
        ),
    ]
