# Generated by Django 5.0 on 2024-02-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_userqueries_alter_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqueries',
            name='AskedWhen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
